//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomizeSettings
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings", IsNullable=false)]
    public partial class SettingsFile
    {
        
        private object profilesField;
        
        private System.Collections.Generic.List<SettingsFileSetting> settingsField;
        
        private string currentProfileField;
        
        private string generatedClassNamespaceField;
        
        private string generatedClassNameField;
        
        private bool useMySettingsClassNameField;
        
        private bool useMySettingsClassNameFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object Profiles
        {
            get
            {
                return this.profilesField;
            }
            set
            {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable=false)]
        public System.Collections.Generic.List<SettingsFileSetting> Settings
        {
            get
            {
                return this.settingsField;
            }
            set
            {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrentProfile
        {
            get
            {
                return this.currentProfileField;
            }
            set
            {
                this.currentProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GeneratedClassNamespace
        {
            get
            {
                return this.generatedClassNamespaceField;
            }
            set
            {
                this.generatedClassNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GeneratedClassName
        {
            get
            {
                return this.generatedClassNameField;
            }
            set
            {
                this.generatedClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UseMySettingsClassName
        {
            get
            {
                return this.useMySettingsClassNameField;
            }
            set
            {
                this.useMySettingsClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseMySettingsClassNameSpecified
        {
            get
            {
                return this.useMySettingsClassNameFieldSpecified;
            }
            set
            {
                this.useMySettingsClassNameFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    public partial class SettingsFileSetting
    {
        
        private SettingsFileSettingDesignTimeValue designTimeValueField;
        
        private SettingsFileSettingValue valueField;
        
        private string nameField;
        
        private string typeField;
        
        private string scopeField;
        
        private bool generateDefaultValueInCodeField;
        
        private bool generateDefaultValueInCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SettingsFileSettingDesignTimeValue DesignTimeValue
        {
            get
            {
                return this.designTimeValueField;
            }
            set
            {
                this.designTimeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SettingsFileSettingValue Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Scope
        {
            get
            {
                return this.scopeField;
            }
            set
            {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool GenerateDefaultValueInCode
        {
            get
            {
                return this.generateDefaultValueInCodeField;
            }
            set
            {
                this.generateDefaultValueInCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenerateDefaultValueInCodeSpecified
        {
            get
            {
                return this.generateDefaultValueInCodeFieldSpecified;
            }
            set
            {
                this.generateDefaultValueInCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    public partial class SettingsFileSettingDesignTimeValue
    {
        
        private string profileField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    public partial class SettingsFileSettingValue
    {
        
        private string profileField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <summary>
    /// Factory class for classes defined in the SettingsSchema schema.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.5.0")]
    public sealed partial class SettingsSchemaFactory
    {
        
        private static string[] _schemas = new string[] {
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<xs:schema attributeFormDefault=\"unqualif" +
                    "ied\" xmlns=\"http://schemas.microsoft.com/VisualStudio/2004/01/settings\" elementF" +
                    "ormDefault=\"qualified\" targetNamespace=\"http://schemas.microsoft.com/VisualStudi" +
                    "o/2004/01/settings\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\r\n  <xs:annotati" +
                    "on>\r\n\t\t\r\n  </xs:annotation>\r\n  <xs:element name=\"SettingsFile\">\r\n    <xs:complex" +
                    "Type>\r\n      <xs:sequence>\r\n        <xs:element name=\"Profiles\" />\r\n        <xs:" +
                    "element name=\"Settings\">\r\n          <xs:complexType>\r\n            <xs:sequence>\r" +
                    "\n              <xs:element maxOccurs=\"unbounded\" name=\"Setting\">\r\n              " +
                    "  <xs:complexType>\r\n                  <xs:sequence>\r\n                    <xs:ele" +
                    "ment minOccurs=\"0\" name=\"DesignTimeValue\">\r\n                      <xs:complexTyp" +
                    "e>\r\n                        <xs:simpleContent>\r\n                          <xs:ex" +
                    "tension base=\"xs:string\">\r\n                            <xs:attribute name=\"Profi" +
                    "le\" type=\"xs:string\" use=\"required\" />\r\n                          </xs:extension" +
                    ">\r\n                        </xs:simpleContent>\r\n                      </xs:compl" +
                    "exType>\r\n                    </xs:element>\r\n                    <xs:element name" +
                    "=\"Value\">\r\n                      <xs:complexType>\r\n                        <xs:s" +
                    "impleContent>\r\n                          <xs:extension base=\"xs:string\">\r\n      " +
                    "                      <xs:attribute name=\"Profile\" type=\"xs:string\" use=\"require" +
                    "d\" />\r\n                          </xs:extension>\r\n                        </xs:s" +
                    "impleContent>\r\n                      </xs:complexType>\r\n                    </xs" +
                    ":element>\r\n                  </xs:sequence>\r\n                  <xs:attribute nam" +
                    "e=\"Name\" type=\"xs:string\" use=\"required\" />\r\n                  <xs:attribute nam" +
                    "e=\"Type\" type=\"xs:string\" use=\"required\" />\r\n                  <xs:attribute nam" +
                    "e=\"Scope\" type=\"xs:string\" use=\"required\" />\r\n                  <xs:attribute na" +
                    "me=\"GenerateDefaultValueInCode\" type=\"xs:boolean\" use=\"optional\" />\r\n\r\n         " +
                    "         \r\n                </xs:complexType>\r\n              </xs:element>\r\n     " +
                    "       </xs:sequence>\r\n          </xs:complexType>\r\n        </xs:element>\r\n     " +
                    " </xs:sequence>\r\n      <xs:attribute name=\"CurrentProfile\" type=\"xs:string\" use=" +
                    "\"required\" />\r\n      <xs:attribute name=\"GeneratedClassNamespace\" type=\"xs:strin" +
                    "g\" use=\"required\" />\r\n      <xs:attribute name=\"GeneratedClassName\" type=\"xs:str" +
                    "ing\" use=\"required\" />\r\n      <xs:attribute name=\"UseMySettingsClassName\" type=\"" +
                    "xs:boolean\" use=\"optional\" />\r\n    </xs:complexType>\r\n  </xs:element>\r\n</xs:sche" +
                    "ma>\r\n"};
        
        private static System.Xml.Schema.XmlSchemaSet _xmlSchemaSet;
        
        private System.Text.StringBuilder _sb;
        
        static SettingsSchemaFactory()
        {
            _xmlSchemaSet = new System.Xml.Schema.XmlSchemaSet();
            for (int i = 0; (i < _schemas.Length); i = (i + 1))
            {
                _xmlSchemaSet.Add(System.Xml.Schema.XmlSchema.Read(new System.IO.StringReader(_schemas[i]), null));
            }
            _xmlSchemaSet.Compile();
        }
        
        /// <summary>
        /// The contents of the SettingsSchema schema and the imported schema.
        /// It is used to check the validity of XML files against the XML schema.
        /// </summary>
        public static string[] Schemas
        {
            get
            {
                return _schemas;
            }
        }
        
        /// <summary>
        /// Gets a compiled schema set containing the SettingsSchema schema and all included schemas.
        /// </summary>
        public static System.Xml.Schema.XmlSchemaSet XmlSchemaSet
        {
            get
            {
                return _xmlSchemaSet;
            }
        }
        
        private void ValidationCallBack(object sender, System.Xml.Schema.ValidationEventArgs e)
        {
            if ((this._sb.Length > 0))
            {
                this._sb.AppendLine();
            }
            this._sb.AppendFormat("Xml Validation Error ({0}, {1}): {2}", e.Exception.LineNumber, e.Exception.LinePosition, e.Message);
        }
        
        private T DoCreate<T>(System.Xml.XmlReader xmlReader)
        
        {
            if ((xmlReader == null))
            {
                throw new System.ArgumentNullException("xmlReader");
            }
            this._sb = new System.Text.StringBuilder();
            System.Xml.XmlReaderSettings xmlReaderSettings = new System.Xml.XmlReaderSettings();
            xmlReaderSettings.ValidationType = System.Xml.ValidationType.Schema;
            xmlReaderSettings.Schemas = XmlSchemaSet;
            xmlReaderSettings.ValidationEventHandler += new System.Xml.Schema.ValidationEventHandler(this.ValidationCallBack);
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
            T result;
            System.Xml.XmlReader validatingXmlReader = System.Xml.XmlReader.Create(xmlReader, xmlReaderSettings);
            try
            {
                result = ((T)(xmlSerializer.Deserialize(validatingXmlReader)));
            }
            finally
            {
                ((System.IDisposable)(validatingXmlReader)).Dispose();
            }
            string errors = this._sb.ToString();
            if ((errors.Length > 0))
            {
                throw new System.Xml.XmlException(errors);
            }
            return result;
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="xmlReader"/>.</typeparam>
        /// <param name="xmlReader">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(System.Xml.XmlReader xmlReader)
        
        {
            return new SettingsSchemaFactory().DoCreate<T>(xmlReader);
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="stream"/>.</typeparam>
        /// <param name="stream">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(System.IO.Stream stream)
        
        {
            if ((stream == null))
            {
                throw new System.ArgumentNullException("stream");
            }
            System.Xml.XmlReader xmlReader = System.Xml.XmlReader.Create(stream);
            try
            {
                return Create<T>(xmlReader);
            }
            finally
            {
                ((System.IDisposable)(xmlReader)).Dispose();
            }
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="path"/>.</typeparam>
        /// <param name="path">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(string path)
        
        {
            if (string.IsNullOrEmpty(path))
            {
                throw new System.ArgumentNullException("path");
            }
            System.Xml.XmlReader xmlReader = System.Xml.XmlReader.Create(path);
            try
            {
                return Create<T>(xmlReader);
            }
            finally
            {
                ((System.IDisposable)(xmlReader)).Dispose();
            }
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="textReader"/>.</typeparam>
        /// <param name="textReader">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(System.IO.TextReader textReader)
        
        {
            if ((textReader == null))
            {
                throw new System.ArgumentNullException("textReader");
            }
            System.Xml.XmlReader xmlReader = System.Xml.XmlReader.Create(textReader);
            try
            {
                return Create<T>(xmlReader);
            }
            finally
            {
                ((System.IDisposable)(xmlReader)).Dispose();
            }
        }
        
        /// <summary>
        /// Creates an object by deserializing the content of an xml document
        /// into an instance of the <typeparamref name="T"/>.
        /// <typeparamref name="T"/> must implement IInitializable to be initialized post creation.
        /// </summary>
        /// <typeparam name="T">The type of the instance to be created from the <paramref name="projectItem"/>.</typeparam>
        /// <param name="projectItem">The XML file project item.</param>
        /// <returns>An instance of type <typeparamref name="T"/>.</returns>"
        public static T Create<T>(Kodeo.Reegenerator.Wrappers.ProjectItem projectItem)
        
        {
            if ((projectItem == null))
            {
                throw new System.ArgumentNullException("projectItem");
            }
            T result = Create<T>(projectItem.FullPath);
            if (typeof(Kodeo.Reegenerator.Generators.Xsd.IInitializable).IsAssignableFrom(typeof(T)))
            {
                ((Kodeo.Reegenerator.Generators.Xsd.IInitializable)(result)).Init(projectItem);
            }
            return result;
        }
    }
}
