// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator
// Generator: CustomizeDesigners.Settings.SettingsRenderer
// Generation date: 2014-02-04 04:14
// Generated by: GATSU-DEV\Tedy.Pranolo
// -------------------------------------------------------

namespace SettingsTest.Properties {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
		public static Settings Default {
			get {
				return defaultInstance;
			}
		}
 		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("12345")]
		public string TestSetting {
			get {
				return ((string)(this["TestSetting"]));
			} 
			set {
				this["TestSetting"] = value;
			} 
		}
 		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("string[]|one,two,three")]
		public SettingsTest.ParsedType Address2 {
			get {
				return ((SettingsTest.ParsedType)(this["Address2"]));
			} 
			set {
				this["Address2"] = value;
			} 
		}
 		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("This will be rendered as \"Address\" and will be readonly even in Scope=User")]
		public string Address {
			get {
				return ((string)(this["Address"]));
			} 
		}

	}
}
